name: Test with Apache Cassandra

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-cassandra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install

    - name: Integration tests
      run: |
        make test-testcontainerscassandra-integration
