name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install

    - name: Src Ruff
      run: |
        poetry run ruff src

    - name: Src Black
      run: |
        poetry run black src --check

    - name: Src Mypy
      run: |
        poetry run mypy src

    - name: Test Ruff
      run: |
        poetry run ruff tests

    - name: Test Black
      run: |
        poetry run black tests --check

    - name: Test Mypy
      run: |
        poetry run mypy tests
